### PR TITLE
Prevent invalid cache

### PR DESCRIPTION
**Pull request by Simage**
Test the response content to ensure it is a valid image prior to returning the "image" to the cache

### CODE REVIEW

**Comment by MatthewDaws** [comment]
Great!  Thank you very much for taking the time to fix this problem, and for doing it an elegant way!

The raw strings for regexs are nice.  I think they aren't needed, but this is only luck, and your approach is better practice.

**Comment by MatthewDaws** [comment]
However, I'm not sure why you added a new line to the log test: it just causes the test to fail on my machine.  I've reverted this, and will now merge and get the tests running in continuous integration.

**Comment by Simage** [comment]
I have a feeling this is likely due to some platform and possibly version differences

The regexes got changed to raw strings to silence warnings from pytest regarding invalid escape sequences

Interestingly the new line was added to the logging test as it was failing on my install without it, possibly the correct action would be to strip the string of whitespace prior to testing, not certain, regardless, fairly minor in any case

**Comment by MatthewDaws** [comment]
You are right.  I added Python 3.8 as a target to my Travis build, and found the same problem.  I don't know why logging has changed between 3.7 and 3.8 (I had a brief look, and found nothing in the release notes etc.)  Anyway, I came up with the same solution: strip whitespace before testing.  That makes the test case work in all versions.

Thanks again.

**Pull request merged**
